settings:
  state_file: /tmp/cbhands_state.yaml
  log_dir: /tmp/cbhands_logs
  pid_dir: /tmp/cbhands_pids
  timeout: 30

services:
  lobby:
    name: "lobby"
    command: "go run cmd/lobby/main.go"
    working_directory: "/home/jk/battles/lobby"
    port: 6001
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    description: "Lobby Service - Table management and WebSocket connections"
    
  dealer:
    name: "dealer"
    command: "go run cmd/dealer/main.go"
    working_directory: "/home/jk/battles/dealer"
    port: 6000
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    description: "Dealer Service - Game logic and rules"
    
  monitor:
    name: "monitor"
    command: "node dist/index.js --port 9001"
    working_directory: "/home/jk/battles/cbhands_monitor_ts"
    port: 9001
    env:
      NODE_ENV: production
      SSL_ENABLED: true
      MONITOR_PORT: 9001
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      LOBBY_HTTP_PORT: 6001
      DEALER_HTTP_PORT: 6000
    description: "Monitor Service - Web control panel and monitoring"
    
  frontend:
    name: "frontend"
    command: "npx serve dist -p 3000"
    working_directory: "/home/jk/battles/battle_hands_ts"
    port: 3000
    env:
      NODE_ENV: production
    description: "Frontend - Battle Hands TypeScript application"