settings:
  state_file: /tmp/cbhands_state.yaml
  log_dir: /tmp/cbhands_logs
  pid_dir: /tmp/cbhands_pids
  timeout: 30

services:
  # Redis - база данных (системный сервис)
  redis:
    name: "redis"
    command: "redis-server --port 6379"
    working_directory: "/tmp"
    port: 6379
    env: {}
    description: "Redis - In-memory data store"
    
  # Dealer - игровая логика (оригинальный)
  dealer:
    name: "dealer"
    command: "go run cmd/dealer/main.go"
    working_directory: "/home/jk/battles/dealer"
    port: 8080  # HTTP API
    grpc_port: 6000  # gRPC API
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    description: "Dealer Service - Game logic and rules (Original)"
    
  # Game Layer Py - прокси над Dealer с Redis логированием
  game_layer_py:
    name: "game_layer_py"
    command: "python -m game_layer_py.main"
    working_directory: "/home/jk/battles/game-layer-py"
    port: 8082  # HTTP API
    env:
      DEALER_HOST: localhost
      DEALER_PORT: 8080
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      API_HOST: 0.0.0.0
      API_PORT: 8082
    description: "Game Layer Py - Dealer Proxy with Redis logging"
    
  # Lobby - управление столами (подключается к game-layer-py)
  lobby:
    name: "lobby"
    command: "go run cmd/lobby/main.go"
    working_directory: "/home/jk/battles/lobby"
    port: 8081  # HTTP API
    grpc_port: 6001  # gRPC API
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DEALER_GRPC_ADDR: localhost:8082  # Подключается к game-layer-py
    description: "Lobby Service - Table management (connects to game-layer-py)"
    
  # Monitor - веб-панель мониторинга
  monitor:
    name: "monitor"
    command: "node dist/index.js --port 9001"
    working_directory: "/home/jk/battles/cbhands_monitor_ts"
    port: 9001
    env:
      NODE_ENV: production
      SSL_ENABLED: true
      MONITOR_PORT: 9001
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      LOBBY_HTTP_PORT: 8081
      DEALER_HTTP_PORT: 8082  # Теперь мониторим game-layer-py
    description: "Monitor Service - Web control panel and monitoring"